# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

In [7]:
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
np.__version__

'2.0.0'

In [9]:
answer(2)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
answer(3)

Z = np.zeros(10)
print(Z)


#### *4. How to find the memory size of any array (★☆☆)

In [15]:
A = np.eye(5)

In [16]:
print(A.size * A.itemsize)
print(A.nbytes)

200
200


In [13]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### *5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [25]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [23]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [28]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [36]:
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [37]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### *9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [43]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### *10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [49]:
np.nonzero([1,2,0,0,4,0])


(array([0, 1, 4]),)

In [13]:
np.info(np.random.randint)

 randint(low, high=None, size=None, dtype=<class 'int'>)

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values

In [14]:
A = np.random.randint(0, 10, size=(5, 5))

In [17]:
A

array([[0, 9, 9, 3, 4],
       [5, 3, 0, 4, 8],
       [6, 7, 2, 7, 3],
       [8, 6, 6, 5, 6],
       [5, 7, 1, 5, 4]])

In [16]:
A.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4]),
 array([1, 2, 3, 4, 0, 1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
        4]))

In [50]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [55]:
np.random.random((3, 3, 3))

array([[[0.81981691, 0.51050071, 0.7131353 ],
        [0.35720185, 0.43730048, 0.54854227],
        [0.74765921, 0.5341723 , 0.92311147]],

       [[0.74781101, 0.78192747, 0.88803597],
        [0.92318805, 0.73812766, 0.17701312],
        [0.97858447, 0.0381458 , 0.79587167]],

       [[0.80978581, 0.10391626, 0.3859458 ],
        [0.15401014, 0.40055807, 0.62789417],
        [0.45680886, 0.0788014 , 0.55647555]]])

In [56]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
Z = np.random.random((10, 10))

In [59]:
print(Z.min())
print(Z.max())

0.007217863094062027
0.9898406103986399


In [60]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [61]:
Z = np.random.random(30)

In [62]:
print(Z.mean())

0.462485009216752


In [63]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. *Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [70]:
Z = np.ones((3, 3))

In [71]:
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [68]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### *16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [91]:
A = np.ones((3, 3))

In [92]:
np.pad(A, (2), 'constant',  
                 constant_values=(0))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.info(np.pad)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
    for each axis.
    ``(before, after)`` or ``((before, after),)`` yields same before
    and after pad for each axis.
    ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
    for all axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'media

In [96]:
Z = np.ones((5,5))
# Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
# print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [93]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
1. Nan
2. False
3. False
4. Nan
5. True
*6. False

In [12]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(np.arange(1, 5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [20]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### *19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.zeros((8, 8))

In [20]:
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1

In [21]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [51]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### *20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
Z = np.random.random((6, 7, 8))

In [85]:
print(99 // (7*8))  # Ищем номер тензора
print(99 % (7*8) // 8)  # Ищем номер строки
print(99 % (7*8) % 8)  # Ищем номер столбца

1
5
3


In [22]:
np.info(np.unravel_index)

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 1

In [82]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [75]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### *21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [100]:
A = np.array([[0, 1], [1, 0]], dtype = np.float16)
np.tile(A, (4, 4))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]], dtype=float16)

In [101]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### *22. Normalize a 5x5 random matrix (★☆☆)

In [118]:
Z = np.random.random((5, 5))
# (Z - np.mean(Z)) / (np.std(Z))
(Z - Z.mean()) / (Z.std())

array([[ 0.46326033, -0.497871  ,  1.1521279 ,  1.16291516,  0.16297538],
       [-1.52483187, -1.35895739,  1.13551561, -0.55867899, -0.73185616],
       [ 1.00855691,  1.25835527,  0.7957774 , -1.44423866,  1.46722488],
       [ 0.39240417,  0.5140848 , -1.22497602, -0.12392526, -1.25203014],
       [-1.33145574,  0.48161352,  0.28456023,  0.98827563, -1.21882597]])

In [119]:
(Z - np.mean(Z)) / (np.std(Z))

array([[ 0.46326033, -0.497871  ,  1.1521279 ,  1.16291516,  0.16297538],
       [-1.52483187, -1.35895739,  1.13551561, -0.55867899, -0.73185616],
       [ 1.00855691,  1.25835527,  0.7957774 , -1.44423866,  1.46722488],
       [ 0.39240417,  0.5140848 , -1.22497602, -0.12392526, -1.25203014],
       [-1.33145574,  0.48161352,  0.28456023,  0.98827563, -1.21882597]])

In [114]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### !23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [30]:
Z = np.random.random((5, 3))
K = np.random.random((3, 2))
np.dot(Z, K), Z @ K

(array([[0.2593853 , 0.55003131],
        [0.70313165, 0.91008359],
        [0.60874799, 0.55291032],
        [0.30983493, 0.24765667],
        [0.48751043, 0.45454196]]),
 array([[0.2593853 , 0.55003131],
        [0.70313165, 0.91008359],
        [0.60874799, 0.55291032],
        [0.30983493, 0.24765667],
        [0.48751043, 0.45454196]]))

In [29]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### *25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [99]:
Z = np.random.random((1, 6))
np.random.seed(42)
Z = Z * 10

In [100]:
Z[(Z > 3) & (Z < 8)] = 0

In [102]:
Z

array([[0.        , 9.50714306, 0.        , 0.        , 1.5601864 ,
        1.5599452 ]])

In [101]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### *26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [106]:
1. 9
2. 10

9
10


In [107]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### *27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [109]:
Z = np.arange(7)

In [118]:
print(Z**Z) # Поэлементное возведение чисел в сами числа
print(2 << Z >> 2)
print(Z <- Z)
print(1j * Z)
print(Z/1/1)
# print(Z < Z > Z) - недопустимая

[    1     1     4    27   256  3125 46656]
[ 0  1  2  4  8 16 32]
[False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j]
[0. 1. 2. 3. 4. 5. 6.]


#### *28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [124]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_6196/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_6196/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_6196/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### *29. How to round away from zero a float array ? (★☆☆)

In [5]:
np.info(np.random.uniform)

 uniform(low=0.0, high=1.0, size=None)

uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

.. note::
    New code should use the `~numpy.random.Generator.uniform`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than or equal to high.  The high limit may be included in the 
    returned array of floats due to floating-point rounding in the 
    equation ``low + (high-low) * rand

In [6]:
Z = np.random.uniform(-10,+10,10)

In [137]:
Z.round()

array([-3., -2., -5.,  7., -3., -4.,  1., -7.,  6., -9.])

In [130]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


In [8]:
Z

array([-6.68692076,  6.8543989 , -6.90472663,  4.50229461, -7.16624367,
        7.62726616,  9.96220839,  9.81790112, -0.85157565,  1.64390183])

In [7]:
np.ceil(np.abs(Z))

array([ 7.,  7.,  7.,  5.,  8.,  8., 10., 10.,  1.,  2.])

In [9]:
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-7.  7. -7.  5. -8.  8. 10. 10. -1.  2.]


In [10]:
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-7.  7. -7.  5. -8.  8. 10. 10. -1.  2.]


#### *30. How to find common values between two arrays? (★☆☆)

In [11]:
Z = np.random.uniform(-10,+10,10).round()
X = np.random.uniform(-10,+10,10).round()
np.intersect1d(Z, X)

array([-0.,  7.])

In [10]:
hint(30)

hint: np.intersect1d


In [13]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### *31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [3]:
hint(31)

hint: np.seterr, np.errstate


In [17]:
np.seterr(all='ignore')

{'divide': 'call', 'over': 'call', 'under': 'call', 'invalid': 'call'}

In [18]:
a = np.random.randint(1, 10, 7)
a / 0

array([inf, inf, inf, inf, inf, inf, inf])

In [19]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### !32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [23]:
np.sqrt(-1),  np.emath.sqrt(-1)

(np.float64(nan), np.complex128(1j))

In [21]:
hint(32)

hint: imaginary number


In [22]:
answer(32)

np.sqrt(-1) == np.emath.sqrt(-1)


#### *33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
np.datetime64('today', 'D') - np.timedelta64(1, 'D') # Yesterday

In [24]:
np.datetime64('today', 'D') # Today

np.datetime64('2024-07-11')

In [27]:
np.datetime64('today', 'D') + np.timedelta64(1, 'D') # Tomorrow

np.datetime64('2024-07-12')

In [28]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### !34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [48]:
delta = np.datetime64('2016-08-01', 'D') - np.datetime64('2016-07-01', 'D')
delta

np.timedelta64(31,'D')

In [52]:
np.datetime64('2016-07-01', 'D') + np.arange(delta)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [53]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### * 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [78]:
A = np.astype(np.random.randint(1, 10, (4, 4)), np.float16)
B = np.astype(np.random.randint(1, 10, (4, 4)), np.float16)
A, B

(array([[1., 9., 7., 3.],
        [3., 7., 3., 6.],
        [4., 4., 6., 6.],
        [4., 6., 5., 4.]], dtype=float16),
 array([[5., 4., 1., 4.],
        [6., 4., 9., 2.],
        [1., 5., 5., 4.],
        [1., 8., 3., 3.]], dtype=float16))

In [68]:
hint(35)

hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)


In [79]:
np.multiply(np.add(A, B), (np.divide(np.negative(A), 2)), out=A)

array([[ -3. , -58.5, -28. , -10.5],
       [-13.5, -38.5, -18. , -24. ],
       [-10. , -18. , -33. , -30. ],
       [-10. , -42. , -20. , -14. ]], dtype=float16)

In [80]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### * 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [99]:
Z = np.random.random((4, 4)) * 100
Z

array([[94.66019796, 92.92832944,  6.30406175, 24.02928063],
       [16.38909549,  4.08585382, 91.45092818, 31.96687035],
       [12.12860752, 34.95367075, 43.37597818, 62.48506341],
       [60.34073305, 99.51058289,  9.55617047, 51.90292207]])

In [100]:
np.floor(Z)

array([[94., 92.,  6., 24.],
       [16.,  4., 91., 31.],
       [12., 34., 43., 62.],
       [60., 99.,  9., 51.]])

In [101]:
np.astype(Z, np.int8)

array([[94, 92,  6, 24],
       [16,  4, 91, 31],
       [12, 34, 43, 62],
       [60, 99,  9, 51]], dtype=int8)

In [105]:
np.ceil(Z) - 1

array([[94., 92.,  6., 24.],
       [16.,  4., 91., 31.],
       [12., 34., 43., 62.],
       [60., 99.,  9., 51.]])

In [106]:
hint(36)

hint: %, np.floor, astype, np.trunc


In [108]:
np.trunc(Z)

array([[94., 92.,  6., 24.],
       [16.,  4., 91., 31.],
       [12., 34., 43., 62.],
       [60., 99.,  9., 51.]])

In [112]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


In [113]:
Z - Z%1

array([[94., 92.,  6., 24.],
       [16.,  4., 91., 31.],
       [12., 34., 43., 62.],
       [60., 99.,  9., 51.]])

#### *37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [14]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### *38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [12]:
np.info(np.fromiter)

fromiter(iter, dtype, count=-1, *, like=None)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iter : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.

    .. versionchanged:: 1.23
        Object and subarray dtypes are now supported (note that the final
        result is not 1-D for a subarray dtype).

count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `co

In [42]:
iterable = (x for x in range(10))
np.fromiter(iterable, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### *39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [51]:
np.setdiff1d(np.linspace(0, 1, 11, endpoint=False), [0])

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [50]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [57]:
X = np.random.random(10)
X.sort()
X

array([0.09736142, 0.18521468, 0.41063301, 0.44626363, 0.48528964,
       0.52014015, 0.59969375, 0.64366777, 0.68568614, 0.97712223])

In [58]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### !41. How to sum a small array faster than np.sum? (★★☆)

In [7]:
A = np.random.randint(0, 1000, (10000000))

In [8]:
%time
A.sum()

CPU times: user 3 μs, sys: 0 ns, total: 3 μs
Wall time: 6.2 μs


np.int64(4995780296)

In [9]:
%time
np.add.reduce(A)

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 5.96 μs


np.int64(4995780296)

In [21]:
hint(41)

hint: np.add.reduce


In [6]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### !42. Consider two random array A and B, check if they are equal (★★☆)

In [3]:
A = np.random.randint(10, size=(10, 10))
B = np.random.randint(10, size=(10, 10))
np.equal(A, B)

array([[False, False,  True,  True, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False,  True,  True,
        False]])

In [20]:
hint(42)

hint: np.allclose, np.array_equal


In [21]:
help(np.allclose)

Help on _ArrayFunctionDispatcher in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    .. warning:: The default `atol` is not appropriate for comparing numbers
                 with magnitudes much smaller than one (see Notes).
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : array_like
        The relative tolerance parameter (see Notes).
    atol : array_like
        The absolute tolerance paramet

In [5]:
np.allclose(A, B), np.array_equal(A, B)

(False, False)

In [10]:
A = np.tile(np.arange(5), (5, 1))
B = np.tile(np.arange(5), (5, 1))

np.allclose(A, B), np.array_equal(A, B)

(True, True)

#### !43. Make an array immutable (read-only) (★★☆)

In [23]:
A = np.arange(1, 10)
A.flags.writeable = False

In [24]:
A[0] = 100

ValueError: assignment destination is read-only

In [25]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### *44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [26]:
A = np.random.randint(1, 100, size=(10, 2))

array([[53, 42],
       [30, 27],
       [65, 63],
       [87, 99],
       [13,  7],
       [35, 60],
       [94, 18],
       [ 6, 80],
       [50, 55],
       [77, 93]])

In [27]:
ro = np.sqrt(A[:, 0] + A[:, 1])
fi = np.arctan(A[:, 1] / A[:, 0])

In [36]:
ro = ro.reshape(-1, 1, )
fi = fi.reshape(-1, 1)

In [38]:
P = np.hstack((ro, fi))
P

array([[ 9.74679434,  0.67012204],
       [ 7.54983444,  0.7328151 ],
       [11.3137085 ,  0.76977443],
       [13.6381817 ,  0.849825  ],
       [ 4.47213595,  0.49394137],
       [ 9.74679434,  1.04272188],
       [10.58300524,  0.18919902],
       [ 9.2736185 ,  1.49593648],
       [10.24695077,  0.83298127],
       [13.03840481,  0.87923938]])

In [39]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### !45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [55]:
np.random.seed(42)
A = np.random.randint(1, 1000, (10))
A, A.max()

(array([103, 436, 861, 271, 107,  72, 701,  21, 615, 122]), np.int64(861))

In [57]:
A[A == A.max()] = 0

In [58]:
A

array([103, 436,   0, 271, 107,  72, 701,  21, 615, 122])

In [54]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


In [59]:
A[A.argmax()] = 0

#### !46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [82]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)
Z = np.hstack((X, Y))
Z

array([[0.  , 0.  ],
       [0.25, 0.  ],
       [0.5 , 0.  ],
       [0.75, 0.  ],
       [1.  , 0.  ],
       [0.  , 0.25],
       [0.25, 0.25],
       [0.5 , 0.25],
       [0.75, 0.25],
       [1.  , 0.25],
       [0.  , 0.5 ],
       [0.25, 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.5 ],
       [1.  , 0.5 ],
       [0.  , 0.75],
       [0.25, 0.75],
       [0.5 , 0.75],
       [0.75, 0.75],
       [1.  , 0.75],
       [0.  , 1.  ],
       [0.25, 1.  ],
       [0.5 , 1.  ],
       [0.75, 1.  ],
       [1.  , 1.  ]])

In [62]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


In [63]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### =>!47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [83]:
hint(47)

hint: np.subtract.outer


In [84]:
np.info(np.subtract.outer)

outer(A, B, /, **kwargs)

Apply the ufunc `op` to all pairs (a, b) with a in `A` and b in `B`.

Let ``M = A.ndim``, ``N = B.ndim``. Then the result, `C`, of
``op.outer(A, B)`` is an array of dimension M + N such that:

.. math:: C[i_0, ..., i_{M-1}, j_0, ..., j_{N-1}] =
   op(A[i_0, ..., i_{M-1}], B[j_0, ..., j_{N-1}])

For `A` and `B` one-dimensional, this is equivalent to::

  r = empty(len(A),len(B))
  for i in range(len(A)):
      for j in range(len(B)):
          r[i,j] = op(A[i], B[j])  # op = ufunc in question

Parameters
----------
A : array_like
    First array
B : array_like
    Second array
kwargs : any
    Arguments to pass on to the ufunc. Typically `dtype` or `out`.
    See `ufunc` for a comprehensive overview of all available arguments.

Returns
-------
r : ndarray
    Output array

See Also
--------
numpy.outer : A less powerful version of ``np.multiply.outer``
              that `ravel`\ s all inputs to 1D. This exists
              primarily for compatibility with old

In [85]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
Z = 1 / np.subtract.outer(A, B)

In [87]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### !48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [88]:
hint(48)

hint: np.iinfo, np.finfo, eps


In [92]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### !49. How to print all the values of an array? (★★☆)

In [95]:
hint(49)

hint: np.set_printoptions


In [97]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


In [98]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [107]:
hint(50)

hint: argmin


In [ ]:
x = 3
A = np.random.randint(1000, size=100)
A[np.argmin(np.abs(A - x))]

In [129]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### !51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [3]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


In [4]:
A = np.zeros(7, [('position', [('x', float, 1),
                               ('y', float, 1)]),
                 ('color', [ ('r', float, 1),
                             ('g', float, 1),
                             ('b', float, 1)])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [5]:
A = np.random.randint(1, 100, size=(100, 2))

In [7]:
hint(52)

hint: np.atleast_2d, T, np.sqrt


In [8]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


In [45]:
Z = np.random.randint(1, 10, size=(100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         6.         7.28010989 ... 7.81024968 3.16227766 3.16227766]
 [6.         0.         8.06225775 ... 5.         5.83095189 3.16227766]
 [7.28010989 8.06225775 0.         ... 4.47213595 4.12310563 6.08276253]
 ...
 [7.81024968 5.         4.47213595 ... 0.         5.38516481 5.        ]
 [3.16227766 5.83095189 4.12310563 ... 5.38516481 0.         2.82842712]
 [3.16227766 3.16227766 6.08276253 ... 5.         2.82842712 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [50]:
Z = np.arange(10, dtype=np.float32)
Z.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [51]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


In [61]:
Z = (np.random.rand(10)*100).astype(np.float32)
ZZ = np.copy(Z)
Z

array([98.140526  , 18.72436   , 51.415676  , 56.424145  , 51.110165  ,
        0.22245698, 68.89809   , 55.081776  , 27.91711   , 77.73897   ],
      dtype=float32)

In [62]:
Y = ZZ.view(np.int32)
Y[:] = ZZ
print(Y)

[98 18 51 56 51  0 68 55 27 77]


In [63]:
Z.astype(np.int32)

array([98, 18, 51, 56, 51,  0, 68, 55, 27, 77], dtype=int32)

#### !54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
hint(54)

hint: np.genfromtxt


In [67]:
np.info(np.genfromtxt)

 genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None,
            skip_header=0, skip_footer=0, converters=None,
            missing_values=None, filling_values=None, usecols=None,
            names=None, excludelist=None,
            deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_',
            autostrip=False, case_sensitive=True, defaultfmt='f%i',
            unpack=None, usemask=False, loose=True, invalid_raise=True,
            max_rows=None, encoding=None, *, ndmin=0, like=None)

Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
    that generators must return byte

In [5]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


In [8]:
from io import StringIO

ss = StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
''')
z = np.genfromtxt(ss, delimiter=',', dtype=np.int8)
z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### !55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [12]:
hint(55)

hint: np.ndenumerate, np.ndindex


In [13]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [16]:
A = np.random.randint(1, 10, size=(3, 3))
for ind, x in np.ndenumerate(A):
    print(ind, x)

(0, 0) 7
(0, 1) 6
(0, 2) 7
(1, 0) 8
(1, 1) 8
(1, 2) 5
(2, 0) 4
(2, 1) 4
(2, 2) 4


In [17]:
np.info(np.ndindex)

 ndindex(*shape)

An N-dimensional iterator object to index arrays.

Given the shape of an array, an `ndindex` instance iterates over
the N-dimensional index of the array. At each iteration a tuple
of indices is returned, the last dimension is iterated over first.

Parameters
----------
shape : ints, or a single tuple of ints
    The size of each dimension of the array can be passed as
    individual parameters or as the elements of a tuple.

See Also
--------
ndenumerate, flatiter

Examples
--------
Dimensions as individual arguments

>>> for index in np.ndindex(3, 2, 1):
...     print(index)
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)

Same dimensions - but in a tuple ``(3, 2, 1)``

>>> for index in np.ndindex((3, 2, 1)):
...     print(index)
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)


Methods:

  ndincr  --  Increment the multi-dimensional index by one.


In [18]:
for index in np.ndindex(3, 3, 3):
    print(index)

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)
(0, 2, 0)
(0, 2, 1)
(0, 2, 2)
(1, 0, 0)
(1, 0, 1)
(1, 0, 2)
(1, 1, 0)
(1, 1, 1)
(1, 1, 2)
(1, 2, 0)
(1, 2, 1)
(1, 2, 2)
(2, 0, 0)
(2, 0, 1)
(2, 0, 2)
(2, 1, 0)
(2, 1, 1)
(2, 1, 2)
(2, 2, 0)
(2, 2, 1)
(2, 2, 2)


#### !56. Generate a generic 2D Gaussian-like array (★★☆)

In [19]:
hint(56)

hint: np.meshgrid, np.exp


In [20]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### !57. How to randomly place p elements in a 2D array? (★★☆)

In [21]:
hint(57)

hint: np.put, np.random.choice


In [23]:
np.info(np.put)

Replaces specified elements of an array with given values.

The indexing works on the flattened target array. `put` is roughly
equivalent to:

::

    a.flat[ind] = v

Parameters
----------
a : ndarray
    Target array.
ind : array_like
    Target indices, interpreted as integers.
v : array_like
    Values to place in `a` at target indices. If `v` is shorter than
    `ind` it will be repeated as necessary.
mode : {'raise', 'wrap', 'clip'}, optional
    Specifies how out-of-bounds indices will behave.

    * 'raise' -- raise an error (default)
    * 'wrap' -- wrap around
    * 'clip' -- clip to the range

    'clip' mode means that all indices that are too large are replaced
    by the index that addresses the last element along that axis. Note
    that this disables indexing with negative numbers. In 'raise' mode,
    if an exception occurs the target array may still be modified.

See Also
--------
putmask, place
put_along_axis : Put elements by matching the array and the index arrays


In [19]:
np.info(np.random.choice)

 choice(a, size=None, replace=True, p=None)

choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

.. warning::
    This function uses the C-long dtype, which is 32bit on windows
    and otherwise 64bit on 64bit platforms (and 32bit on 32bit ones).
    Since NumPy 2.0, NumPy's default integer is 32bit on 32bit platforms
    and 64bit on 64bit platforms.


Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.


In [55]:
a = np.arange(5)
Z = [10, 20, 30]
np.put(a, np.random.choice(np.arange(len(Z)), size=len(Z)), Z, mode='clip')
a

array([30,  1, 10,  3,  4])

In [46]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


In [67]:
dim = 7
element = 0
nelements = 5

Z = np.ones((dim, dim))
random_indexes = np.random.choice(np.arange(dim*dim), nelements, replace=False)
np.put(Z, random_indexes, element)
Z

array([[0., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1.]])

#### !58. Subtract the mean of each row of a matrix (★★☆)

In [69]:
hint(58)

hint: mean(axis=,keepdims=)


In [70]:
np.info(np.mean)

Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
out : ndarray, optional
    Alternate output array in which to place the result.  The def

In [75]:
Z = np.random.randint(1, 10, (5, 5))
Z - np.mean(Z, axis=1, keepdims=True)

array([[ 2.6, -2.4,  3.6, -2.4, -1.4],
       [-2. ,  0. ,  0. ,  4. , -2. ],
       [ 3.2, -2.8, -3.8,  0.2,  3.2],
       [-4. ,  2. ,  4. , -3. ,  1. ],
       [ 2.6, -3.4,  0.6, -2.4,  2.6]])

In [74]:
answer(58)

# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### !59. How to sort an array by the nth column? (★★☆)

In [79]:
np.info(np.argsort)

Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

Parameters
----------
a : array_like
    Array to sort.
axis : int or None, optional
    Axis along which to sort.  The default is -1 (the last axis). If None,
    the flattened array is used.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.
order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second

In [80]:
hint(59)

hint: argsort


In [81]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


In [83]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 3 0]
 [9 9 7]
 [4 8 3]]
[[3 3 0]
 [4 8 3]
 [9 9 7]]


#### ->!60. How to tell if a given 2D array has null columns? (★★☆)

In [90]:
hint(60)

hint: any, ~


In [97]:
answer(60)

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


In [5]:
Z = np.random.randint(0,3,(3,10))
np.isnan(Z).all(axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

#### 61. *Find the nearest value from a given value in an array (★★☆)

In [28]:
k = 7
np.random.seed(42)
Z = np.random.uniform(0,1,10)
Z[np.argmin(np.abs(Z - k))], Z.flat[np.abs(Z - k).argmin()]

(np.float64(0.9507143064099162), np.float64(0.9507143064099162))

In [10]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. !Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [31]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K',
    casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if r

In [32]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


In [33]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)